---
# test dehydrated certificate request for domain
- name: Run dehydrated test {{ item }}
  ansible.builtin.shell: |
    dehydrated --config {{ dehydratedconf.path }} -d "{{ item }}" -c || true
  register: cmd_results
  changed_when: false
  become: "{{ lihas_become | default('no') }}"
- name: Check if staging certificate exists {{ item }}
  ansible.builtin.stat:
    path: "/var/lib/dehydrated/certs-staging/{{ item | regex_replace(' .*', '') }}/cert.pem"
  register: stat_results
  changed_when: false
  become: "{{ lihas_become | default('no') }}"
- name: Add successful certificates {{ item }}
  ansible.builtin.set_fact:
    dehydrated_domains: "{{ dehydrated_domains + [item] }}"
  when: stat_results.stat.exists
  changed_when: false
