#!/bin/bash
# ansible managed
# dehydrated renew, mit mk-job wenn vorhanden, mit '--now' ohne Pause

NOW=0
TEMP=`getopt -o h --long now -- "$@"`
if [ $? != 0 ] ; then echo "Unknown parameter, read the source" >&2 ; exit 1 ; fi
eval set -- "$TEMP"
while true ; do
  case "$1" in
    --now)    NOW=1; shift 1;;
    --) shift ; break ;;
    *) echo "Unknown parameter $1, read the source" ; exit 1 ;;
  esac
done

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

PROXY_SRV="" # e.g. http://1.2.3.4:3128"

export http_proxy=$PROXY_SRV
export https_proxy=$PROXY_SRV

[ -x /usr/bin/mk-job ] && mkjob=yes

if [ "x$NOW" == "x0" ]; then
# wait random but minimal 10 seconds
sleep $[ ( $RANDOM % 50 ) + 10 ]
fi

# Die letsencrypt server sind manchmal nicht gut erreichbar, darum 'n' Versuche. Aber nicht zu viele
# wegen drohender Sperre für eine Woche, falls ein anderer Fehler vorliegt.
if [ "$mkjob" = yes ]
then
  sed '/^#\|^ \|^$/d' /etc/dehydrated/domains.txt | while read domain
  do
    status=1
    for try in {1..2}
    do
      mk-job dehydrated_$(awk '{print $1}' <<<${domain}) /usr/bin/dehydrated -c -d "$domain" | logger 2>&1 
      [ ${PIPESTATUS[0]} = 0 ] && break 
      [ "x$NOW" == "x1" ] && break 
      [ $try = 2 ] && echo "Letsencrypt Renew didn't work for $domain, check syslog."
    done 
  done
else
  status=1
  for try in {1..2}
  do
    dehydrated -c | logger 2>&1 
    [ ${PIPESTATUS[0]} = 0 ] && break
    [ "x$NOW" == "x1" ] && break 
    [ $try = 2 ] && echo "Letsencrypt Renew didn't work(completely), check syslog."
  done
fi

# cleanup
find /var/lib/dehydrated/certs/ -type f -empty -exec rm '{}' \; 
